#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Move to a script
xrandr --output HDMI-1 --primary --mode 2560x1440 --rotate normal --output DP-1-1 --mode 2560x2880 --rotate normal --left-of HDMI-1 --output DP-1-2 --off

~/.config/polybar/launch.sh --hack &

~/.fehbg &

picom -cf &
