#! /bin/sh

userresources=$HOME/.Xresources

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX &
bspc monitor DP-1-1 -d X &
bspc wm -O HDMI-1 DP-1-1

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

picom -cf &

~/.screenlayout/default.sh
~/.config/polybar/launch.sh
~/.fehbg &
