# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/ps6hc66v73kl33wkc1vsjl4kzghn2mnq-hm-session-vars.fish

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations

    # Aliases
    alias .c 'cd ~/.config'
    alias cat bat
    alias g git
    alias ga 'git add'
    alias gb 'git branch'
    alias gc 'git commit'
    alias gcl 'git clone'
    alias gco 'git checkout'
    alias gd 'git diff'
    alias gl 'git pull'
    alias gp 'git push'
    alias gst 'git status'
    alias la 'exa --icons --group-directories-first --header --long --all'
    alias ll 'exa --icons --group-directories-first --header --long'
    alias lt 'exa --icons --group-directories-first --tree --level=2'

    # Interactive shell initialisation
    /nix/store/xs72wvbjhyghfnzdyb384s6d9b09c0jj-fzf-0.62.0/bin/fzf --fish | source

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/Users/devonwalker/.local/share/fish/home-manager_generated_completions" $post
    end

end

# Load Starship prompt
starship init fish | source

# Load zoxide
zoxide init --cmd j fish | source
